apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: apicontagemxpkube 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apicontagemxpkube 
    spec:
      containers:
        - name: apicontagemxpkube 
          image: groffeazuredevops.azurecr.io/apicontagemxpkube
          ports:
          - containerPort: 80