apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mackenziekube0 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mackenziekube0 
    spec:
      containers:
        - name: mackenziekube0 
          image: groffeazuredevops.azurecr.io/mackenziekube0
          ports:
          - containerPort: 80