apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: kubernetesfcnuvem 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetesfcnuvem 
    spec:
      containers:
        - name: kubernetesfcnuvem 
          image: groffeazuredevops.azurecr.io/kubernetesfcnuvem
          ports:
          - containerPort: 80